### ISSUE TITLE
[Need Help] background reset to black on non text area

### ISSUE THREAD

**Issue by tokikanno** [zcodes/vim-colors-basic#1]
![image](https://user-images.githubusercontent.com/130347/28447859-1e22701a-6e06-11e7-865c-343ef2284b91.png)

### Issue

The background color reset to black on non-text area.
Don't know if I got anything wrong in the .vimrc file 😞 

### Enviornment

Host: Ubuntu 16.04 + vim 8.0 
Client: OSX iTerm2

### .vimrc

```
 call plug#begin('~/.vim/plugged')
 " Make sure you use single quotes

 Plug 'mhinz/vim-grepper'

 " Initialize plugin system
 call plug#end()

 set t_Co=256
 " set background=dark
 colorscheme basic-dark
 " highlight Normal ctermbg=NONE
 " highlight nonText ctermbg=NONE

 set backspace=indent,eol,start

 "" Encoding
 set encoding=utf-8
 set fileencoding=utf-8
 set fileencodings=utf-8
 set bomb
 set binary

 syntax on
 set ai
 set nu

 set shiftwidth=4
 set tabstop=4
 set softtabstop=4
 set expandtab

 set hlsearch
 set incsearch
 set ignorecase
 set smartcase
 set smartindent
 " set cursorline
 " set cursorcolumn
 " highlight CursorLine ctermbg=54 ctermfg=None
 " highlight CursorColumn ctermbg=58 ctermfg=None

 set fileformats=unix,dos,mac

 " disable mouse control
 " set mouse-=a

 noremap <silent> <C-S>          :update<CR>
 vnoremap <silent> <C-S>         <C-C>:update<CR>
 inoremap <silent> <C-S>         <C-O>:update<CR>
```

**Comment by zcodes** [comment]
sorry, i don't known yet. I use this theme in windows and ubuntu 16.04 with a gui or from console, but i never get this problem.

may be you can use ':colorscheme basic-dark' refresh it by manual and see what happends ...

**Comment by tokikanno** [comment]
I found what's wrong and how to solve it
It's caused by tmux BCE (background color eraser) behavior

https://stackoverflow.com/questions/6427650/vim-in-tmux-background-color-changes-when-paging

Maybe you could consider adding this solution into your color schema file? 😃  (or maybe in readme)

**Comment by zcodes** [comment]
thank you.
